version: "3"

volumes:
  tyrant-api-redis: 
networks:
  umbrella-net:
    name: "umbrella-net"
    external: false
name: tyrant-services
services:
  tyrant-api:
    build:
      context: .
      dockerfile: ./Dockerfile  
    restart: on-failure
    depends_on: 
      - tyrant-api-mongo
    volumes:
      - ../:/tyrant-api
    expose:
      - 17323
    ports:
      - 17323:17323 
    networks:
      - umbrella-net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "17323" ]
      interval: 5s
      timeout: 15s
      retries: 1
    environment:
      - MONGO_RS_URL=mongodb://rs-tyrant-mongo:27017,rs-tyrant-mongo:27018,rs-tyrant-mongo:27019/tyrant?replicaSet=rs
      - REDIS_PORT=6379
      - REDIS_HOST=tyrant-api-redis
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - RABBITMQ_URL=amqp://admin:admin@pendulum-services-pendulum-app-rabbitmq-1:5672
      - RABBITMQ_SCIENTIST_OPERATIONS_TO_SOLVE_QUEUE=scientist-operations-to-solve
      - RABBITMQ_SCIENTIST_OPERATIONS_SOLVED=scientist-operations-solved
      - STUCK_SCIENTIST_OPERATIONS_AS_FAILED_INTERVAL=20 seconds
      - STUCK_SCIENTIST_OPERATIONS_AS_FAILED_LIMIT=200
      - STUCK_SCIENTIST_OPERATIONS_AS_FAILED_WINDOW=10
      - SCIENTIST_OPERATIONS_NOTIFICATION_WEBHOOK=http://neptune-services-neptune-app-1:18323/api/tyrant-api/notification
      - ENCRYPTION_PASSWORD=123456789
  tyrant-api-redis:
    image: redis
    volumes:
      - tyrant-api-redis:/data
    expose:
      - 6379
    ports:
      - 6379:6379      
    restart: unless-stopped
    networks:
      - umbrella-net
  tyrant-api-mongo:
    image: azguerrero/mongo-replicaset
    container_name: rs-tyrant-mongo
    environment:
      - HOST_NAME=rs-tyrant-mongo
    expose:
      - 27017
      - 27018
      - 27019
    ports:
      - 27017:27017 
      - 27018:27018 
      - 27019:27019 

    volumes:
      - ./db:/data/db
    networks:
      - umbrella-net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "27019" ]
      interval: 5s
      timeout: 100s
      retries: 5
