version: "3"

volumes:
  tyrant-api-redis:
  tyrant-api-rabbitmq:

networks:
  umbrella-net:
    name: "umbrella-net"
    external: false
services:
  tyrant-api-environment:
    build:
      context: .
      dockerfile: ./Dockerfile   
    volumes:
      - ../:/tyrant-api-environment
    networks:
      - umbrella-net
  tyrant-api-redis:
    image: redis
    volumes:
      - tyrant-api-redis:/data
    expose:
      - 6379
    ports:
      - 6379:6379      
    restart: unless-stopped
    networks:
      - umbrella-net
  tyrant-api-mongo:
    image: azguerrero/mongo-replicaset
    container_name: rs-mongo
    expose:
      - 27017
      - 27018
      - 27019
    ports:
      - 27017:27017 
      - 27018:27018 
      - 27019:27019 

    volumes:
      - ./db:/data/db
    networks:
      - umbrella-net
  tyrant-api-rabbitmq:
    image: azguerrero/rabbitmq-deduplication
    container_name: tyrant-api-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin 
    volumes:
      - tyrant-api-rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - umbrella-net
